export const ADD_USER_MESSAGE = 'ADD_USER_MESSAGE';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const ADD_QUICK_REPLIES = 'ADD_QUICK_REPLIES';
export const DELETE_QUICK_REPLIES = 'DELETE_QUICK_REPLIES';
export const ADD_BOT_MESSAGE = 'ADD_BOT_MESSAGE';