export const ADD_USER_MESSAGE = 'ADD_USER_MESSAGE';
export const SEND_USER_MESSAGE = 'SEND_USER_MESSAGE';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const ADD_WELCOME_MESSAGE = 'ADD_WELCOME_MESSAGE';
export const SEND_EVENT_QUERY_MESSAGE = 'SEND_EVENT_QUERY_MESSAGE';
export const ADD_QUICK_REPLIES = 'ADD_QUICK_REPLIES';
export const DELETE_QUICK_REPLIES = 'DELETE_QUICK_REPLIES';